# Generated by Django 5.0.4 on 2024-09-03 15:39

import main_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_hero_delete_discountedproduct_discountedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashHero',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.hero', main_app.models.RechargeEnergyMixin),
        ),
        migrations.CreateModel(
            name='SpiderHero',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.hero', main_app.models.RechargeEnergyMixin),
        ),
    ]
