# Generated by Django 5.0.4 on 2024-08-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    def set_age_group(apps, schema_editor):
        person_model = apps.get_model('main_app', 'Person')

        people = person_model.objects.all()

        for person in people:
            if person.age <= 12:
                person.age_group = 'Child'

            elif 13 <= person.age <= 17:
                person.age_group = 'Teen'

            elif person.age >= 18:
                person.age_group = 'Adult'

            person.save()

    def set_age_group_default(apps, schema_editor):
        person_model = apps.get_model('main_app', 'Person')

        people = person_model.objects.all()

        for person in people:
            person.age_group = person_model.get_field('age_group').default
            person.save()

    dependencies = [
        ('main_app', '0010_person'),
    ]

    operations = [
        migrations.RunPython(set_age_group, set_age_group_default)
    ]
