# Generated by Django 5.0.4 on 2024-08-23 18:33

from django.db import migrations


class Migration(migrations.Migration):

    def set_rarity(apps, schema_editor):
        items_model = apps.get_model('main_app', 'Item')
        all_items = items_model.objects.all()

        for item in all_items:
            if item.price <= 10:
                item.rarity = 'Rare'

            elif 11 <= item.price <= 20:
                item.rarity = 'Very Rare'

            elif 21 <= item.price <= 30:
                item.rarity = 'Extremely Rare'

            elif item.price >= 31:
                item.rarity = 'Mega Rare'

            item.save()

    def set_rarity_default(apps, schema_editor):
        item_model = apps.get_model('main_app', 'Item')
        all_items = item_model.objects.all()

        for item in all_items:
            item.rarity = item_model.get_field('rarity').default
            item.save()


    dependencies = [
        ('main_app', '0012_item'),
    ]

    operations = [
        migrations.RunPython(set_rarity, set_rarity_default)
    ]
