# Generated by Django 5.0.4 on 2024-08-23 19:56

from django.db import migrations


def set_price(apps, schema_editor):
    MULTIPLAYER = 120

    smartphone_model = apps.get_model('main_app', 'Smartphone')
    all_smartphones = smartphone_model.objects.all()

    for smartphone in all_smartphones:
        smartphone.price = len(smartphone.brand) * MULTIPLAYER
        smartphone.save()


def set_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    all_smartphones = smartphone_model.objects.all()

    for smartphone in all_smartphones:
        if smartphone.price < 750:
            smartphone.category = 'Cheap'

        else:
            smartphone.category = 'Expensive'

        smartphone.save()


def set_all_columns(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)


def reverse_filling_of_columns_category_and_price(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    all_smartphones = smartphone_model.objects.all()

    for smartphone in all_smartphones:
        smartphone.category = smartphone_model.get_field('category').default
        smartphone.price = smartphone_model.get_field('price').default
        smartphone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_all_columns, reverse_filling_of_columns_category_and_price)
    ]
