# Generated by Django 5.0.4 on 2024-08-24 16:41

from django.db import migrations
from django.utils import timezone


def set_delivery_and_warranty(apps, schema_editor):
    orders_model = apps.get_model('main_app', 'Orders')
    all_orders = orders_model.objects.all()

    for order in all_orders:
        if order.status == 'Pending':
            order.delivery = order.order_date + timezone.timedelta(days=3)

        elif order.status == 'Completed':
            order.warranty = '24 months'

        elif order.status == 'Cancelled':
            order.delete()

    orders_model.objects.bulk_update(all_orders, ['delivery', 'warranty'])


def set_reverse_delivery_and_warranty(apps, schema_editor):
    orders_model = apps.get_model('main_app', 'Orders')
    all_orders = orders_model.objects.all()

    for order in all_orders:
        order.delivery = orders_model._meta.get_field('delivery').default
        order.warranty = None

    orders_model.objects.bulk_update(all_orders, ['delivery', 'warranty'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_orders'),
    ]

    operations = [
        migrations.RunPython(set_delivery_and_warranty, set_reverse_delivery_and_warranty)
    ]
