# Generated by Django 5.0.4 on 2024-08-25 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='price_without_discount',
            new_name='price_with_discount',
        ),
    ]
