"""Adding connection between tables

Revision ID: 0971e3434bbc
Revises: a0d9d8e36833
Create Date: 2024-09-08 17:25:40.864453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0971e3434bbc'
down_revision: Union[str, None] = 'a0d9d8e36833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'city_id')
    # ### end Alembic commands ###
